sudo: required
services:
  - docker

before_install:
  - docker build -t testinguser883/docker-react -f Dockerfile.dev .

script:
  - docker run testinguser883/docker-react npm run test -- --coverage

deploy:
  provider: azure_web_apps
  username: "$AZURE_WA_USERNAME"
  site: "$AZURE_WA_SITE"
  on:
    branch: master
