sudo: required
services:
  - docker

before_install:
  - docker build -t testinguser883/docker-react -f Dockerfile.dev .

script:
  - docker run testinguser883/docker-react npm run test -- --coverage
