version: '3'

services:
  web:
    # image: 'react-app'
    image: 'my.image.name:rc2'
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    # image: 'react-app'
    # image: 'my.image.name:rc2'
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "test"]
